name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Baut die Seite im jekyll/builder container.
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - uses: actions/upload-artifact@v2
      with:
        name: Artifact download
        path: ${{ github.workspace }}/_site
        
    - uses: hakierspejs/jekyll-screenshot-github-action@master    
    - uses: actions/upload-artifact@v2
      with:
       name: screenshot
       path: /home/runner/work/_temp/_github_home/screenshot.png
